name: CI/CD pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # CI - Build and Push Docker image to Docker Hub
  push-to-registry:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ist-app .

      # Step 4: Tag and Push to Docker Hub
      - name: Tag and Push Docker image
        run: |
          docker tag ist-app kalsoomsarfraz/ist-app:latest
          docker push kalsoomsarfraz/ist-app:latest

  # CD - Pull the Docker image and run the container
  deploy-to-server:
    runs-on: self-hosted

    steps:
      # Step 1: Pull the latest Docker image
      - name: Pull Docker image
        run: sudo docker pull kalsoomsarfraz/ist-app:latest

      # Step 2: Remove old container if exists
      - name: Delete old Docker container
        run: sudo docker rm -f ist-app-container || true 

      # Step 3: Run a new Docker container with the latest image
      - name: Run Docker container
        run: sudo docker run -d -p 80:80 --name ist-app-container kalsoomsarfraz/ist-app
