name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
        
      - name: SSH into server and set up environment
        run: |
         ssh -v -o StrictHostKeyChecking=no kalsoom-sarfraz@192.168.217.128 <<EOF
         set -e
         cd /home/kalsoom-sarfraz/Sample-Node.js-Application 
         git pull origin master
         npm install
         npm audit fix
         npm run build
         EOF
