name: CD pipeline 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
     
      - name: pull docker image
        run: sudo docker pull kalsoomsarfraz/ist-app:latest

      - name: Delete old docker container
        run: sudo docker rm -f ist-app-container || true 
        
      - name: run docker container
        run: sudo docker run -d -p 80:80 --name ist-app-container kalsoomsarfraz/ist-app

      
          
