name: CI pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ist-app .

      # Step 4: Tag and Push to Docker Hub
      - name: Tag and Push Docker image
        run: |
          docker tag ist-app kalsoomsarfraz/ist-app:latest
          docker push kalsoomsarfraz/ist-app:latest
