name: Build Node.js Application with Docker (No Dockerfile in Repo)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   push to registry:
            build:
            runs-on: self-hosted

            steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Log in to Docker
            uses: docker/login-action@v2
            with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create Dockerfile
        run: |
          echo "FROM node:22" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY package*.json ./" >> Dockerfile
          echo "RUN npm install" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile
          echo 'CMD ["npm", "start"]' >> Dockerfile

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run Docker container
        run: docker run -d --name myapp -p 3000:3000 myapp

      - name: Test application
        run: docker exec myapp npm test

      - name: Stop and clean up container
        if: always()
        run: |
          docker stop myapp
          docker rm myapp
