name: Build Node.js Application with Docker (No Dockerfile in Repo)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Dockerfile
        run: |
          echo "FROM node:22" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY package*.json ./" >> Dockerfile
          echo "RUN npm install" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile
          echo 'CMD ["npm", "start"]' >> Dockerfile

      - name: Build Docker image
        run: docker build -t nodejs-app .

      - name: Run Docker container
        run: docker run -d --name nodejs-app -p 3000:3000 nodejs-app

      - name: Test application
        run: docker exec nodejs-app npm test

      - name: Stop and clean up container
        if: always()
        run: |
          docker stop nodejs-app
          docker rm nodejs-app
