name: Build Node.js Application with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push-to-registry:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build and push Docker image
        run: docker build -t Ist-App .
      - name: push to dockerhub
        run: docker push kalsoomsarfraz/Ist-App:latest
